// <auto-generated />
using System;
using MenuManagementSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MenuManagementSystem.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20210323191753_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("MenuManagementSystem.Models.Cook", b =>
                {
                    b.Property<int>("CookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("CookId");

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("MenuManagementSystem.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MealTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("MealId");

                    b.HasIndex("CookId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MenuManagementSystem.Models.Meal", b =>
                {
                    b.HasOne("MenuManagementSystem.Models.Cook", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId");
                });
#pragma warning restore 612, 618
        }
    }
}
